name: Build Cheat Engine

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Setup job variables
        uses: allenevans/set-env@v2.0.1
        with:
          LAZARUS_VERSION: 2.0.10
          FPC_VERSION: 3.2.0
      - uses: actions/checkout@v2
      - name: Get Lazarus dependencies
        shell: bash
        id: get-dependencies
        run: echo "::set-output name=dependencies::$(node ./.github/workflows/scripts/getPackages.js)"
      - name: Install Lazarus
        uses: gcarreno/setup-lazarus@v3.0.2
        with:
          lazarus-version: ${{ env.LAZARUS_VERSION }}
          include-packages: ${{ steps.get-dependencies.outputs.dependencies }}
      - name: Install 32bit compat
        shell: bash
        run: wget https://downloads.sourceforge.net/project/lazarus/Lazarus%20Windows%2064%20bits/Lazarus%20${LAZARUS_VERSION}/lazarus-${LAZARUS_VERSION}-fpc-${FPC_VERSION}-cross-i386-win32-win64.exe -O ${GITHUB_WORKSPACE}/32bit.exe && cd ${GITHUB_WORKSPACE} && ./32bit.exe /VERYSILENT /DIR=${RUNNER_TEMP}/lazarus
        env:
          LAZARUS_VERSION: ${{ env.LAZARUS_VERSION }}
          FPC_VERSION: ${{ env.FPC_VERSION }}
      - name: Build 64-Bit O4 AVX2
        shell: cmd
        run: lazbuild --build-mode="Release 64-bit O4 AVX2" --no-write-project "Cheat Engine/cheatengine.lpi"
      - name: Zip artifact
        shell: cmd
        run: 7z a -tzip release.zip * -r
        working-directory: "./Cheat Engine/bin"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 7.x.x
          files: "./Cheat Engine/bin/release.zip"
          body: |
            Note: Daily build from last commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
